name:  📝 ドキュメント改善・修正提案
description: ドキュメントの改善や修正提案をする
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ドキュメントの改善や修正をありがとうございます。  
        どの部分を改善・修正したいか、具体的にご記入ください。

  - type: textarea
    id: doc_section
    attributes:
      label: 改善・修正対象のドキュメント箇所
      description: 例）READMEのインストール手順、Wikiの○○ページなど
      placeholder: 修正したい箇所を記載してください
    validations:
      required: true

  - type: textarea
    id: proposed_change
    attributes:
      label: 改善・修正内容の詳細
      description: 実際にどう改善・修正したいかを記述してください
      placeholder: 例）インストール手順にバージョン番号を追記したい
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 変更の理由・背景
      description: なぜ改善・修正が必要かを簡単に説明してください
      placeholder: 例）最新バージョンで手順が変わったため
